### ISSUE TITLE
Converting letters depends on the default language

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang-gutenberg#24] opened 2018-11-07 15:22 UTC
## Plugins activated & WordPress version

Polylang Pro 2.4-beta1
WordPress 5.0-beta3 (block mode editor)

## Issue description

Converts letters like ö, ä, ü to oe, ae, ue. for de_DE languages works only if the de_DE language is assigned as default language.
But when assigning de_DE language as default language it impacts the other languages. Example: for the English, the ä is converted to ae instead of a.

See also: https://github.com/polylang/polylang-pro/issues/122

## Steps to reproduce the issue

1. Add 2 languages, the German (de_DE) and the English language.
2. Choose the German as default langauge.
3. Create an English post with the ä letter as below. Once the post is saved the ä has been converted to ae. It should be a.

![convert-letters-bloc-editor](https://user-images.githubusercontent.com/19824724/48140168-81828d80-e2a8-11e8-8ac0-4f43635c5956.png)

**Comment by Chouby** [comment] 2019-03-26 09:07
Does it work as expected without Polylang?

**Comment by manooweb** [comment] 2019-04-02 14:28
See also https://github.com/polylang/polylang-pro/issues/183

Wordpress 5.1.1
Gutenberg 5.3 which override block editor integrated in WP 5.1.1

**Without Polylang**
- website in german
- user profile in english

ä is converted to a as expected in the permalink ie a

**With Polylang & without Polylang Gutenberg**

- website in english
- PLL default language in german
- user profile in english

ä is converted to a as expected in the permalink ie a

**With Polylang & with Polylang Gutenberg**

- website in english
- PLL default language in german
- user profile in english

Exactly like the second case. PLL Gutenberg does not change anything about the post title. So it's logic

Except if I'm wrong everything seems to be ok.

**Comment by manooweb** [comment] 2019-04-03 07:30
I close this issue. The problem can be reproduced without PLL Gutenberg
See also polylang/polylang-pro#183

**Closed by manooweb** 2019-04-03 07:30 UTC
